### PR TITLE
Fix operation dispatching allowing nested operations

### LINKED ISSUE #345: cache-and-network seems to not fire the network
I am brand new to urql and while testing it out in my app, it appears to me that cache-and-network is not working as I had expected.

I created a different issue than #299 as that issue was primarily concerned about the executeQuery part of useQuery. 

My expectations from reading the docs is that it would return what is in cache, then it would also fire a network request in the background, update the cache, and cause a re-render if the data has changed.

Let me know if those expectations are incorrect.

I created this codesandbox to demonstrate.  https://codesandbox.io/s/youthful-fast-7g373

I created two components that each utilize the same query and have the requestPolicy set to cache-and-network.  We are grabbing the first new story from hackernews using graphqlhub api. 

When I load a component for the first time, it shows me the network request.  However, when moving between the components, it is only pulling from cache and not firing the network request.

I added debugExchange after cacheExchange.  It only logs on the first network request, which I believe is demonstrating that the cacheExchange is not forwarding on.

Below is a video:

Fgi0NS0wxe

### PR DESCRIPTION
**Pull request by kitten**
Fix #345

We run the entire exchange pipeline synchronously,
since that's predictable, which is how Wonka's
sources work.

When an exchange dispatches an operation, for
instance with reexecuteOperation, this operation
is hence run immediately, which can be confusing
and lead to state that disagrees with itself,
since the operation is essentially then "nested".

Instead what we want is to queue operations up
if they're dispatched nestedly, so from inside
an exchange, and flush this queue after the
original dispatch has completed.

### CODE REVIEW

**Comment by JoviDeCroock** [comment]
This does not seem to solve the problem yet. It comes into the debugExchange located on position two but does not reach the fetchExchange when switching between Test1 and 2

https://codesandbox.io/s/cool-ishizaka-9k4pf

**Comment by JoviDeCroock** [comment]
I implemented this fix into the sandbox and this does not seem to execute a network request just yet. Judging through the debugExchange it does go through passed the deduplication but does not go to fetch.

https://codesandbox.io/s/cool-ishizaka-9k4pf

**Comment by kitten** [comment]
@JoviDeCroock Just tested it in your sandbox 👍  the modification seems to actually be working correctly as far as I can tell. Your sandbox was just missing the actual change in `client.js` 😅

**Comment by JoviDeCroock** [comment]
Yes, codesandbox didn't save my change for some reason. Not getting lucky with my statements today. Just going to approve this. 😄

**Comment by parkerziegler** [comment]
Woah this is really interesting, thanks for the explanation @kitten. So if I'm understanding correctly, the main issue for #345 came down to the fact that, when the `requestPolicy` was set to `"cache-and-network"`, the `cacheExchange` is actually calling that `reexecuteOperation` function, which sends the _same operation_ (by key that is, but with `requestPolicy` set to `"network-only"`) into the pipeline. This is the "nested operation" case you describe. The solution then is to queue all operations coming into the exchange and flush them once the original, non-nested operation has completed. Does this feel like a fair summary? Just want to make sure I really understand this, since this issue sent me spinning for a little while.

**Comment by kitten** [comment]
@parkerziegler Yes, that's a fair summary. Since `reexecuteOperation` eventually calls directly into dispatching the operation on the subject, which would then run through the exchanges synchronously as part of `reexecuteOperation`'s call stack even.

> The solution then is to queue all operations coming into the exchange and flush them once the original, non-nested operation has completed

Yep, that's the whole solution. If we're already processing an operation (i.e. are in the exchange pipeline) then we queue up the operation and flush them synchronously after the original one completed.

**Pull request merged**
