### PR TITLE
Add setter for fetchOptions updates

### LINKED ISSUE #234: Feature request: allow to return promise in fetchOptions function
there are often cases when in order to obtain a JWT token, we have to call an async function. For example with AWS amplify: https://aws-amplify.github.io/docs/js/authentication#retrieve-current-session

it would be nice if urql would allow us to return fetch options from the `fetch`  asynchronously.

currently fetch options type is defined here: https://github.com/FormidableLabs/urql/blob/9a49818c4a54583d1f457772323dab58c78211df/src/client.ts#L32

and as you can see it only accepts a static object or a function which returns synchronously.

### PR DESCRIPTION
**Pull request by andyrichardson**
Fix #234

### CODE REVIEW

**Comment by kitten** [comment]
@andyrichardson Do you think this is safe to merge now that @JoviDeCroock has written a comprehensive auth example/guide in #361?

**Comment by andyrichardson** [comment]
@kitten no objections here, I'll un-draft the PR and get CI triggered

**Comment by JoviDeCroock** [comment]
@andyrichardson updating the snapshots should suffice for the CI

**Comment by kitten** [comment]
Hiya, I think I actually confused this PR 💕😅 Do we still need this PR given the auth exchange example in the guide?

**Comment by kitten** [comment]
Closing due to inactivity

**Pull request closed without merging**
