### PR TITLE
(chore) - remove useDevtoolsContext

### PR DESCRIPTION
**Pull request by JoviDeCroock**
Relies on publishing of: https://github.com/FormidableLabs/urql-devtools-exchange/pull/1

Removes 60gzipped bytes

### CODE REVIEW

**Comment by parkerziegler** [comment]
Looks great to me @JoviDeCroock! Definitely merge ready once FormidableLabs/urql-devtools-exchange#1 is published!

**Comment by andyrichardson** [comment]
I've merged your changes in `urql-devtools-exchange`!

**Comment by andyrichardson** [comment]
I think we should hold off merging this until the devtools exchange changes have been published

**Comment by kitten** [comment]
@andyrichardson definitely 👍 otherwise we'd diverge and we don't want that confusion on master for sure

**Pull request merged**
