### PR TITLE
Do not merge: Next Release

### PR DESCRIPTION
**Pull request by kitten**
**Do not merge please!**

This is just here to collect some comments on the changes and have an overview over all changes 👍 

### Current list of changes

- **Exchanges!** :100:💱 A link-like abstraction to process operations independently from the client
- In-flight request deduplication (via `dedupExchange`): Deduplicates in-flight requests via the operation's key
- Extracted the main-caching logic into `cacheExchange`
- Added cancellation support to `httpExchange`
- Added `CombinedError` that holds `graphQLErrors` and `networkError`
- Added `subscription` prop to `ClientWrapper` and a matching helper
- Added subscription support via `subscriptionExchange` (transport agnostic)
- Added `transformExchange` option to client
- Pass observables all the way down to make cancellation work on unmount

### CODE REVIEW

**Comment by kitten** [comment]
Since I haven't looked into generating bundlesizes yet, here's the diff of bundled src files against master instead 😅

```
 src/components/client.tsx     | 157 ++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------------
 src/modules/cache-exchange.ts |  53 +++++++++++++++++++++++++++++++++
 src/modules/client.ts         | 251 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------------------------------------------------------------------------
 src/modules/dedup-exchange.ts |  55 ++++++++++++++++++++++++++++++++++
 src/modules/default-cache.ts  |  32 ++++++++++++++++++++
 src/modules/error.ts          |  58 ++++++++++++++++++++++++++++++++++++
 src/modules/http-exchange.ts  |  90 +++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/utils/zip-observables.ts  |  45 ++++++++++++++++++++++++++++
 8 files changed, 513 insertions(+), 228 deletions(-)
```

**Comment by jwright** [comment]
Is there anyway this can be tagged with and deployed to npm as `next2` or something else? Is this waiting on something that I may be able to help out with?

**Comment by kitten** [comment]
@jwright yes, I’ll try to release a new prerelease soon 👍 other than that this branch is actually almost ready to go.

You can also try out all changes in “next” plus #98 by installing “urquelle”, which might become our unstable release line

**Comment by jwright** [comment]
Thanks for all the work @kitten. I very much appreciate this great library.

**Comment by kitten** [comment]
@jwright @kenwheeler Published updates as `v0.3.0-next2` under the `next` tag. https://www.npmjs.com/package/urql/v/0.3.0-next2

**Pull request closed without merging**
