### PR TITLE
(docs) - Redirects

### PR DESCRIPTION
**Pull request by JoviDeCroock**
This is an attempt at redirects for the pages we've moved around in our docs-split up

### CODE REVIEW

**Comment by wgolledge** [comment]
Good idea!

**Comment by JoviDeCroock** [comment]
Currently not working yet it doesn't respect the base-url yet.

**Comment by kitten** [comment]
@JoviDeCroock wondering what this outputs 🤔 if we want the proper redirection codes we may have to look into some changes on the AWS bucket side

**Comment by JoviDeCroock** [comment]
@kitten currently redirects to the absolute url (without normal prefix) wanted to introduce this as an in-between fix so we could introduce the split-up docs already.

**Comment by kitten** [comment]
This kind of seems to work as it uses `http-equiv="refresh"` as expected. The generation of them seems to be extremely flawed though and it outputs: `/open-source/urql//docs/basics/core`, which isn't normalised or correct in this case.

**Review by kitten — APPROVED** [review]

**Pull request merged**
