### PR TITLE
(refactor) - remove unused typings file

### PR DESCRIPTION
**Pull request by JoviDeCroock**
Saw this file was unused, removed it. Little pull request, hope you don't mind

### CODE REVIEW

**Comment by JoviDeCroock** [comment]
Sailci is failing on irrelevant parts :/

**Comment by kitten** [comment]
@JoviDeCroock Can you rebase this onto our new `master`? :)

**Comment by JoviDeCroock** [comment]
@kitten Newby question I suppose but should I always do `git push --force` since rebasing always seems to do odd things in sourcetree :/ sorry for the q

**Comment by kitten** [comment]
So if you have an upstream remote set up for this repo then you can pull master from there or reset hard on our master and rebase / merge from that 👍

**Comment by JoviDeCroock** [comment]
I did that, I pulled `upstream/master` went on my `refactor/pruneUnused` branch. Rebased on top of master (on `refactor/` still). I think I'm doing something wrong since it also indicates a change on files I did not touch.

**Comment by kitten** [comment]
I'll just add you as a member since you've contributed a lot so that you can simplify your work flow and push branches directly 👍

**Comment by JoviDeCroock** [comment]
Oh, thanks. Glad to help out though, feel free to reach out if you need help on something.

**Comment by kitten** [comment]
@JoviDeCroock You should have an invite :+1:

**Comment by JoviDeCroock** [comment]
Allright, thanks! Accepted it. This looks good now though, or am I missing something?

**Comment by kitten** [comment]
This shows an unrelated change but that should prune away :+1: all good

**Pull request merged**
