### PR TITLE
(docs) - fix file upload exchange example

### PR DESCRIPTION
**Pull request by lukasluecke**
add missing "variables." prefix to path map entries

### CODE REVIEW

**Comment by lukasluecke** [comment]
I am also not sure about the 1-based index for the path map - in the spec they use 0-based in their examples. Not that it changes anything, was just wondering .

**Comment by lukasluecke** [comment]
Also the example seems to have diverted from the "real" fetchExchange quite a bit already, would you want me to update the code as well, so it more closely resembles the current structure (and you can just copy / paste the "file upload" part into it)?

**Comment by JoviDeCroock** [comment]
The variables should not be needed, I've implemented a codesandbox where you can see it at work.

**Comment by lukasluecke** [comment]
@JoviDeCroock Really weird.. I can see your example working, but when I tried it in my project, the `paths` were missing the `variables.` part, and this change fixed it.. 🤔 I'll try to find out what's happening there.

**Comment by JoviDeCroock** [comment]
Maybe your server implementation is using another spec?

**Comment by lukasluecke** [comment]
Doesn't all this happen before anything is sent to the server though?

```
files.forEach(paths => {
    console.log(paths);
    map[++i] = paths;
});
```

In your codesandbox, this logs `["variables.file"]` as expected, but using the code from the guide (which seems to be pretty identical to your example) locally logs `["file"]`, which then doesn't work.

**Comment by JoviDeCroock** [comment]
Maybe something changed in the extract-files implementation? It's correct for the current state of that plugin. I'm not at my pc but I'll test it tomorrow

**Comment by lukasluecke** [comment]
@JoviDeCroock I found the difference - in your example you use `mutate({ variables: { file } })` to call the mutation - but the signature of the mutator returned by `useMutation` expects a call like `mutate({file})` - which is also what I'm using, and therefore adding the prefix is necessary.

```js
export declare const useMutation: <T = any, V = object>(query: string | DocumentNode) => [UseMutationState<T>, (variables?: V | undefined, context?: Partial<OperationContext> | undefined) => Promise<OperationResult<T>>];
```

Do you agree, or am I missing something here?

**Comment by lukasluecke** [comment]
No worries, my implementation is working for me now, so there's no rush. Just wanted to let you know 🙂

**Comment by JoviDeCroock** [comment]
Oh, then yours is good to merge fi we updater the sandbox

**Comment by JoviDeCroock** [comment]
Thank you a lot for this PR @lukasluecke I'm sorry it took so long for me to get to it, updated the sandboxes and stuff! Thanks a lot!

**Pull request merged**
