### PR TITLE
Add guide on using urql outside of React.

### PR DESCRIPTION
**Pull request by parkerziegler**
This PR is currently WiP, but I figured I'd get feedback early from folks. The purpose of this PR is to create a guide for using `urql` outside of React. Specifically, I'm focusing on highlighting how to use `urql`'s `client` directly, since that's the easiest way for non-React consumers to get access to the core functionality.

Currently, I have two examples for using `urql` with NodeJS. I'd like to add a basic example with Vue as well before merging.

The biggest issue I see with using `urql` in non-React codebases is the peer dependency on React, and the way our internal references to `react` require it being installed even in a Node or Vue environment where it isn't used. I'd be curious to see if our tree-shaking works out in a Vue environment. Regardless, this makes me think of two things:

1. We should probably have a Caveats section in this doc that makes this plain. It's not a big deal if you're just using `urql` to write quick little Node scripts / CLIs for personal use, but the peerDep on `react` makes me question how useful this is.
2. As @kitten suggested in #253, there may be a time in the future where we consider splitting the `client` into a separate package to support non-React consumers who just want access to the client. But I don't think we're there yet 😅 We should continue to focus on making this the best it can be for React.

### CODE REVIEW

**Comment by parkerziegler** [comment]
> Do we want this to even include the HTTP server bits? This doesn't showcase a spec- compliant GraphQL server, so it may be a confusing example

I'll remove these. They're included purely because `http` is used in the CodeSandbox examples to write a response to the client (so that the user sees something), but I agree that they're just implementation details that are confusing in this context 👍

**Comment by dusty** [comment]
I've just been experimenting with urql.  We have an app that is angular 1 and react.  All new things are in react, but we have a ton of old angular components that we don't have time to rewrite.  Here is what I ended up using in my experimentation.  So far I just played with queries.

I export my urql client that I created and then pull that in to an angular factory.

```
import angular from 'angular'
import { pipe, subscribe } from 'wonka'
import { createRequest } from 'urql'
import { client } from '@/graphql'  // this is the client I created

angular.module('common').factory('GraphQL', GraphQL)

GraphQL.$inject = ['$q']
function GraphQL($q) {
  return { query }

  function query({ query, variables }) {
    const request = createRequest(query, variables)
    return $q(resolve =>
      pipe(
        client.executeQuery(request),
        subscribe(resolve)
      )
    ).then(({ data, error }) => (error ? $q.reject(error) : data))
  }
}
```

Somewhere else

```
return GraphQL.query({
      query,
      variables: { id }
    }).then(data => data.theThing)
```

If we ever decide to move forward with urql (we are currently playing with apollo) I'd be happy to share whatever we end up doing.

But, it sounds like you were asking for feedback, so I thought I'd pass this along.

**Comment by parkerziegler** [comment]
Thanks for the example @dusty. I'm glad to see that folks already seem to be figuring a lot of what this guide will try to formalize. I think we're currently planning to keep the examples to Node and Vue, but if there's more interest I'd definitely be happy to have an Angular or Ember example in there as well; I'd probably just want to ensure we were showing examples in the latest versions of those frameworks.

**Comment by parkerziegler** [comment]
@JoviDeCroock definitely. I never did see an invite come through, would you mind resending it?

**Pull request merged**
