### PR TITLE
Add package-lock to gitignore

### PR DESCRIPTION
**Pull request by jamesplease**
If you'd like I can also PR an `.npmrc` that disables the creation of these things.

### CODE REVIEW

**Comment by kenwheeler** [comment]
Should this co-exist with a yarn.lock?

**Comment by jmeas** [comment]
Sure. I’ll add that too

**Comment by ryan-roemer** [comment]
@kenwheeler -- Can you explain your comment more? I understand this PR as committing to yarn for dev, leaving `yarn.lock` in git. (which I'm cool with)

**Comment by kenwheeler** [comment]
@ryan-roemer I misunderstood the original intent, I originally thought it was adding package-lock

**Pull request merged**
